### ISSUE TITLE
Different answer appears in repl.it

### ISSUE THREAD

**Issue by astania** [learn-co-curriculum/phase-0-pac-2-while-loop#1]
## Link to Canvas

https://learning.flatironschool.com/courses/4596/pages/repetition-the-while-loop?module_item_id=289858

## Issue Subtype

- [ ] Master branch code
- [x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
let count = 0; // Initialize a counter variable; note that we need to use `let` here
while (count < 3) { //A Boolean expression that uses the counter to decide whether to keep looping
  console.log(`I am the ${count}, I love to count!`); // The work the loop does
  count = count + 1; // Update the counter variable; this keeps track of how many times the loop has executed
}
```

### Concern

You say that it produces:
"I am the 0, I love to count!
I am the 1, I love to count!
I am the 2, I love to count!"
but it actually produces

"I am the 0, I love to count!
I am the 1, I love to count!
I am the 2, I love to count!
3"
(with the extra 3 at the end)
idk, I could be wrong/dumb, but that's what my repl.it shows me. 

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by ihollander** [comment]
Hi @astania - thanks for pointing this out! 

You're absolutely right, running that code in repl.it produces that output. The reason for this is that in addition to displaying the `console.log` statements, repl.it also shows what the last line of code evaluates to. In this code snippet, the last line of code that is evaluated is `count = count + 1`, which will be `3` by the time our `while` loop is finished, so that's why the `3` shows up at the end. I'll update the readme to make a note of that. 

We appreciate your feedback! 💙
